from sqlalchemy import Column, Integer, String, JSON, DateTime, Index, Text, Boolean
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.session import Base

class Game(Base):
    __tablename__ = "games"

    # NHL gamePk like 2024020206
    game_id    = Column(Integer, primary_key=True, index=True)

    # Canonical game metadata
    game_date_utc = Column(DateTime, nullable=False, index=True)
    status    = Column(String, nullable=False, default="SCHEDULED")  # SCHEDULED/LIVE/FINAL/COMPLETE/ARCHIVED

    # Teams and score (scores may be unknown until game ends)
    away_team = Column(String, nullable=False, index=True)
    home_team = Column(String, nullable=False, index=True)
    away_score= Column(Integer, nullable=True)
    home_score= Column(Integer, nullable=True)

    # Optional extras
    recap_url = Column(String, nullable=True)   # link to official recap (do not store article text)
    scorers   = Column(JSON, nullable=True)     # optional list of strings or objects
    raw       = Column(JSON, nullable=True)     # store full boxscore JSON if desired

    # Claude-generated content
    recap_text = Column(Text, nullable=True)     # Magazine-style summary generated by Claude
    recap_generated = Column(Boolean, default=False)
    summary_line = Column(String, nullable=True) # One-sentence lead (e.g., "Couture's PP tally was the difference")

    # Processing state tracking
    basic_stats_fetched = Column(Boolean, default=False)
    reddit_fetched = Column(Boolean, default=False)
    videos_fetched = Column(Boolean, default=False)
    quotes_fetched = Column(Boolean, default=False)

    # Timestamps for processing stages
    status_updated_at = Column(DateTime, nullable=True, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)  # When T+4h processing finished
    archived_at = Column(DateTime, nullable=True)   # When T+24h archival completed

    # Standings context (stored as snapshot)
    standings_snapshot = Column(JSON, nullable=True)  # Pacific Division standings at time of game

    # Next game preview
    next_opponent = Column(String, nullable=True)
    next_game_date = Column(DateTime, nullable=True)
    next_game_storyline = Column(String, nullable=True)

    # Relationship to Player model (per-game player stats)
    players = relationship(
        "Player",
        back_populates="game",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    # Relationships to new models
    comments = relationship("Comment", cascade="all, delete-orphan", passive_deletes=True)
    videos = relationship("Video", cascade="all, delete-orphan", passive_deletes=True)
    quotes = relationship("Quote", cascade="all, delete-orphan", passive_deletes=True)
    milestones = relationship("Milestone", cascade="all, delete-orphan", passive_deletes=True)

    __table_args__ = (
        # Helpful composite index for queries like: find all Sharks home games in a window
        Index("ix_games_home_away_date", "home_team", "away_team", "game_date_utc"),
        # Index for finding games that need processing
        Index("ix_games_status_updated", "status", "status_updated_at"),
    )