# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prospects/v1/prospects.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'prospects/v1/prospects.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprospects/v1/prospects.proto\x12\x0cprospects.v1\"\xf0\x01\n\x08Prospect\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x01(\t\x12\x12\n\ndraft_year\x18\x04 \x01(\x05\x12\x15\n\rdraft_overall\x18\x05 \x01(\x05\x12\x0e\n\x06league\x18\x06 \x01(\t\x12\x11\n\tteam_name\x18\x07 \x01(\t\x12\x1a\n\x12\x65liteprospects_url\x18\x08 \x01(\t\x12\x16\n\x0ehas_live_stats\x18\t \x01(\x08\x12\x31\n\x0e\x63urrent_season\x18\n \x01(\x0b\x32\x19.prospects.v1.SeasonStats\"\xc3\x01\n\x0bSeasonStats\x12\x0e\n\x06season\x18\x01 \x01(\t\x12\x14\n\x0cgames_played\x18\x02 \x01(\x05\x12\r\n\x05goals\x18\x03 \x01(\x05\x12\x0f\n\x07\x61ssists\x18\x04 \x01(\x05\x12\x0e\n\x06points\x18\x05 \x01(\x05\x12\x12\n\nplus_minus\x18\x06 \x01(\x05\x12\x0b\n\x03pim\x18\x07 \x01(\x05\x12\x12\n\nupdated_at\x18\x08 \x01(\t\x12)\n\x06goalie\x18\t \x01(\x0b\x32\x19.prospects.v1.GoalieStats\"\x8b\x01\n\x0bGoalieStats\x12\x0c\n\x04wins\x18\x01 \x01(\x05\x12\x0e\n\x06losses\x18\x02 \x01(\x05\x12\x11\n\tot_losses\x18\x03 \x01(\x05\x12\x10\n\x08shutouts\x18\x04 \x01(\x05\x12\r\n\x05saves\x18\x05 \x01(\x05\x12\r\n\x05shots\x18\x06 \x01(\x05\x12\x0b\n\x03gaa\x18\x07 \x01(\x01\x12\x0e\n\x06sv_pct\x18\x08 \x01(\x01\"8\n\x14ListProspectsRequest\x12\x10\n\x08position\x18\x01 \x01(\t\x12\x0e\n\x06league\x18\x02 \x01(\t\"B\n\x15ListProspectsResponse\x12)\n\tprospects\x18\x01 \x03(\x0b\x32\x16.prospects.v1.Prospect\" \n\x12GetProspectRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"?\n\x13GetProspectResponse\x12(\n\x08prospect\x18\x01 \x01(\x0b\x32\x16.prospects.v1.Prospect2\xbf\x01\n\x0fProspectService\x12X\n\rListProspects\x12\".prospects.v1.ListProspectsRequest\x1a#.prospects.v1.ListProspectsResponse\x12R\n\x0bGetProspect\x12 .prospects.v1.GetProspectRequest\x1a!.prospects.v1.GetProspectResponseB[ZYgithub.com/adenjo6/nhl-faninsights/prospect-service/internal/gen/prospects/v1;prospectsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prospects.v1.prospects_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZYgithub.com/adenjo6/nhl-faninsights/prospect-service/internal/gen/prospects/v1;prospectsv1'
  _globals['_PROSPECT']._serialized_start=47
  _globals['_PROSPECT']._serialized_end=287
  _globals['_SEASONSTATS']._serialized_start=290
  _globals['_SEASONSTATS']._serialized_end=485
  _globals['_GOALIESTATS']._serialized_start=488
  _globals['_GOALIESTATS']._serialized_end=627
  _globals['_LISTPROSPECTSREQUEST']._serialized_start=629
  _globals['_LISTPROSPECTSREQUEST']._serialized_end=685
  _globals['_LISTPROSPECTSRESPONSE']._serialized_start=687
  _globals['_LISTPROSPECTSRESPONSE']._serialized_end=753
  _globals['_GETPROSPECTREQUEST']._serialized_start=755
  _globals['_GETPROSPECTREQUEST']._serialized_end=787
  _globals['_GETPROSPECTRESPONSE']._serialized_start=789
  _globals['_GETPROSPECTRESPONSE']._serialized_end=852
  _globals['_PROSPECTSERVICE']._serialized_start=855
  _globals['_PROSPECTSERVICE']._serialized_end=1046
# @@protoc_insertion_point(module_scope)
