# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from prospects.v1 import prospects_pb2 as prospects_dot_v1_dot_prospects__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in prospects/v1/prospects_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProspectServiceStub:
    """ProspectService is the internal, service-to-service read API for Sharks
    prospect data. It is consumed over gRPC by the Python FastAPI gateway, which
    caches results in Redis and re-exposes them to the browser as REST. Browsers
    never speak gRPC directly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProspects = channel.unary_unary(
                '/prospects.v1.ProspectService/ListProspects',
                request_serializer=prospects_dot_v1_dot_prospects__pb2.ListProspectsRequest.SerializeToString,
                response_deserializer=prospects_dot_v1_dot_prospects__pb2.ListProspectsResponse.FromString,
                _registered_method=True)
        self.GetProspect = channel.unary_unary(
                '/prospects.v1.ProspectService/GetProspect',
                request_serializer=prospects_dot_v1_dot_prospects__pb2.GetProspectRequest.SerializeToString,
                response_deserializer=prospects_dot_v1_dot_prospects__pb2.GetProspectResponse.FromString,
                _registered_method=True)


class ProspectServiceServicer:
    """ProspectService is the internal, service-to-service read API for Sharks
    prospect data. It is consumed over gRPC by the Python FastAPI gateway, which
    caches results in Redis and re-exposes them to the browser as REST. Browsers
    never speak gRPC directly.
    """

    def ListProspects(self, request, context):
        """ListProspects returns the curated Sharks prospect roster, optionally
        filtered by position and/or league. Both filters are optional; empty means
        "no filter".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProspect(self, request, context):
        """GetProspect returns a single prospect by its internal id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProspectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProspects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProspects,
                    request_deserializer=prospects_dot_v1_dot_prospects__pb2.ListProspectsRequest.FromString,
                    response_serializer=prospects_dot_v1_dot_prospects__pb2.ListProspectsResponse.SerializeToString,
            ),
            'GetProspect': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProspect,
                    request_deserializer=prospects_dot_v1_dot_prospects__pb2.GetProspectRequest.FromString,
                    response_serializer=prospects_dot_v1_dot_prospects__pb2.GetProspectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prospects.v1.ProspectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('prospects.v1.ProspectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProspectService:
    """ProspectService is the internal, service-to-service read API for Sharks
    prospect data. It is consumed over gRPC by the Python FastAPI gateway, which
    caches results in Redis and re-exposes them to the browser as REST. Browsers
    never speak gRPC directly.
    """

    @staticmethod
    def ListProspects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prospects.v1.ProspectService/ListProspects',
            prospects_dot_v1_dot_prospects__pb2.ListProspectsRequest.SerializeToString,
            prospects_dot_v1_dot_prospects__pb2.ListProspectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/prospects.v1.ProspectService/GetProspect',
            prospects_dot_v1_dot_prospects__pb2.GetProspectRequest.SerializeToString,
            prospects_dot_v1_dot_prospects__pb2.GetProspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
