"""create games table

Revision ID: 4ca6be1a75d1
Revises: 
Create Date: 2025-07-22 22:10:15.283901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca6be1a75d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
    "games",
    sa.Column("game_id", sa.Integer(), primary_key=True, nullable=False),
    sa.Column("away_team", sa.String(), nullable=False),
    sa.Column("home_team", sa.String(), nullable=False),
    sa.Column("away_score", sa.Integer(), nullable=False),
    sa.Column("home_score", sa.Integer(), nullable=False),
    sa.Column("scorers", sa.JSON(), nullable=False),
    sa.Column("raw", sa.JSON(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    # ### end Alembic commands ###
