"""add game_date_utc status recap_url; rework players key

Revision ID: 5bae33282c94
Revises: 4ca6be1a75d1
Create Date: 2025-08-30 16:05:28.759802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bae33282c94'
down_revision: Union[str, Sequence[str], None] = '4ca6be1a75d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('game_date_utc', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('games', sa.Column('status', sa.String(), nullable=False, server_default='SCHEDULED'))
    op.add_column('games', sa.Column('recap_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'recap_url')
    op.drop_column('games', 'status')
    op.drop_column('games', 'game_date_utc')
    # ### end Alembic commands ###
