-- Creates the `prospects` database for the Go prospect-service.
--
-- The prospect-service owns its own schema (goose migrations embedded in the
-- binary) and must not share tables with the FastAPI backend's `nhl` database,
-- so it gets a separate database inside the same postgres container.
--
-- Files in /docker-entrypoint-initdb.d run ONLY on first container init (empty
-- data dir). If your postgres_data volume already exists, this won't run —
-- create the DB manually instead:
--   docker exec nhl-postgres createdb -U nhluser prospects
CREATE DATABASE prospects OWNER nhluser;
