// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Prospect struct {
	ID                   int64              `json:"id"`
	FullName             string             `json:"full_name"`
	Position             string             `json:"position"`
	DraftYear            *int32             `json:"draft_year"`
	DraftOverall         *int32             `json:"draft_overall"`
	League               string             `json:"league"`
	Source               string             `json:"source"`
	HockeytechClientCode *string            `json:"hockeytech_client_code"`
	HockeytechPlayerID   *string            `json:"hockeytech_player_id"`
	EliteprospectsUrl    *string            `json:"eliteprospects_url"`
	TeamName             *string            `json:"team_name"`
	Active               bool               `json:"active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type ProspectSeasonStat struct {
	ID          int64              `json:"id"`
	ProspectID  int64              `json:"prospect_id"`
	Season      string             `json:"season"`
	TeamName    *string            `json:"team_name"`
	GamesPlayed int32              `json:"games_played"`
	Goals       int32              `json:"goals"`
	Assists     int32              `json:"assists"`
	Points      int32              `json:"points"`
	PlusMinus   int32              `json:"plus_minus"`
	Pim         int32              `json:"pim"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
	Wins        *int32             `json:"wins"`
	Losses      *int32             `json:"losses"`
	OtLosses    *int32             `json:"ot_losses"`
	Shutouts    *int32             `json:"shutouts"`
	Saves       *int32             `json:"saves"`
	Shots       *int32             `json:"shots"`
	Gaa         pgtype.Numeric     `json:"gaa"`
	SvPct       pgtype.Numeric     `json:"sv_pct"`
}
