// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSeasonStats = `-- name: CountSeasonStats :one
SELECT COUNT(*) FROM prospect_season_stats WHERE season = $1
`

// How many stat rows exist for a season label. Used to decide whether the
// "current" season has data yet or the API should fall back to the previous
// season (off-season / pre-season window).
func (q *Queries) CountSeasonStats(ctx context.Context, season string) (int64, error) {
	row := q.db.QueryRow(ctx, countSeasonStats, season)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getProspect = `-- name: GetProspect :one
SELECT
    p.id,
    p.full_name,
    p.position,
    p.draft_year,
    p.draft_overall,
    p.league,
    p.source,
    p.eliteprospects_url,
    COALESCE(s.team_name, p.team_name) AS team_name,
    s.season,
    s.games_played,
    s.goals,
    s.assists,
    s.points,
    s.plus_minus,
    s.pim,
    s.wins,
    s.losses,
    s.ot_losses,
    s.shutouts,
    s.saves,
    s.shots,
    s.gaa,
    s.sv_pct,
    s.fetched_at
FROM prospects p
LEFT JOIN prospect_season_stats s
       ON s.prospect_id = p.id AND s.season = $1
WHERE p.id = $2
`

type GetProspectParams struct {
	Season string `json:"season"`
	ID     int64  `json:"id"`
}

type GetProspectRow struct {
	ID                int64              `json:"id"`
	FullName          string             `json:"full_name"`
	Position          string             `json:"position"`
	DraftYear         *int32             `json:"draft_year"`
	DraftOverall      *int32             `json:"draft_overall"`
	League            string             `json:"league"`
	Source            string             `json:"source"`
	EliteprospectsUrl *string            `json:"eliteprospects_url"`
	TeamName          *string            `json:"team_name"`
	Season            *string            `json:"season"`
	GamesPlayed       *int32             `json:"games_played"`
	Goals             *int32             `json:"goals"`
	Assists           *int32             `json:"assists"`
	Points            *int32             `json:"points"`
	PlusMinus         *int32             `json:"plus_minus"`
	Pim               *int32             `json:"pim"`
	Wins              *int32             `json:"wins"`
	Losses            *int32             `json:"losses"`
	OtLosses          *int32             `json:"ot_losses"`
	Shutouts          *int32             `json:"shutouts"`
	Saves             *int32             `json:"saves"`
	Shots             *int32             `json:"shots"`
	Gaa               pgtype.Numeric     `json:"gaa"`
	SvPct             pgtype.Numeric     `json:"sv_pct"`
	FetchedAt         pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetProspect(ctx context.Context, arg GetProspectParams) (GetProspectRow, error) {
	row := q.db.QueryRow(ctx, getProspect, arg.Season, arg.ID)
	var i GetProspectRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Position,
		&i.DraftYear,
		&i.DraftOverall,
		&i.League,
		&i.Source,
		&i.EliteprospectsUrl,
		&i.TeamName,
		&i.Season,
		&i.GamesPlayed,
		&i.Goals,
		&i.Assists,
		&i.Points,
		&i.PlusMinus,
		&i.Pim,
		&i.Wins,
		&i.Losses,
		&i.OtLosses,
		&i.Shutouts,
		&i.Saves,
		&i.Shots,
		&i.Gaa,
		&i.SvPct,
		&i.FetchedAt,
	)
	return i, err
}

const listIngestableProspects = `-- name: ListIngestableProspects :many
SELECT id, full_name, position, hockeytech_client_code, hockeytech_player_id
FROM prospects
WHERE active = true AND source = 'HOCKEYTECH'
ORDER BY id
`

type ListIngestableProspectsRow struct {
	ID                   int64   `json:"id"`
	FullName             string  `json:"full_name"`
	Position             string  `json:"position"`
	HockeytechClientCode *string `json:"hockeytech_client_code"`
	HockeytechPlayerID   *string `json:"hockeytech_player_id"`
}

// HockeyTech-sourced active prospects the cron should refresh. position
// decides which bulk feed a prospect is matched against (topscorers vs
// topgoalies).
func (q *Queries) ListIngestableProspects(ctx context.Context) ([]ListIngestableProspectsRow, error) {
	rows, err := q.db.Query(ctx, listIngestableProspects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngestableProspectsRow{}
	for rows.Next() {
		var i ListIngestableProspectsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Position,
			&i.HockeytechClientCode,
			&i.HockeytechPlayerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProspects = `-- name: ListProspects :many
SELECT
    p.id,
    p.full_name,
    p.position,
    p.draft_year,
    p.draft_overall,
    p.league,
    p.source,
    p.eliteprospects_url,
    COALESCE(s.team_name, p.team_name) AS team_name,
    s.season,
    s.games_played,
    s.goals,
    s.assists,
    s.points,
    s.plus_minus,
    s.pim,
    s.wins,
    s.losses,
    s.ot_losses,
    s.shutouts,
    s.saves,
    s.shots,
    s.gaa,
    s.sv_pct,
    s.fetched_at
FROM prospects p
LEFT JOIN prospect_season_stats s
       ON s.prospect_id = p.id AND s.season = $1
WHERE p.active = true
  AND ($2::text IS NULL OR p.position = $2)
  AND ($3::text   IS NULL OR p.league   = $3)
ORDER BY s.points DESC NULLS LAST, p.full_name ASC
`

type ListProspectsParams struct {
	Season   string  `json:"season"`
	Position *string `json:"position"`
	League   *string `json:"league"`
}

type ListProspectsRow struct {
	ID                int64              `json:"id"`
	FullName          string             `json:"full_name"`
	Position          string             `json:"position"`
	DraftYear         *int32             `json:"draft_year"`
	DraftOverall      *int32             `json:"draft_overall"`
	League            string             `json:"league"`
	Source            string             `json:"source"`
	EliteprospectsUrl *string            `json:"eliteprospects_url"`
	TeamName          *string            `json:"team_name"`
	Season            *string            `json:"season"`
	GamesPlayed       *int32             `json:"games_played"`
	Goals             *int32             `json:"goals"`
	Assists           *int32             `json:"assists"`
	Points            *int32             `json:"points"`
	PlusMinus         *int32             `json:"plus_minus"`
	Pim               *int32             `json:"pim"`
	Wins              *int32             `json:"wins"`
	Losses            *int32             `json:"losses"`
	OtLosses          *int32             `json:"ot_losses"`
	Shutouts          *int32             `json:"shutouts"`
	Saves             *int32             `json:"saves"`
	Shots             *int32             `json:"shots"`
	Gaa               pgtype.Numeric     `json:"gaa"`
	SvPct             pgtype.Numeric     `json:"sv_pct"`
	FetchedAt         pgtype.Timestamptz `json:"fetched_at"`
}

// Roster for the public list, joined to the current season's stats (if any).
// @season is the current season label; position/league are optional filters.
func (q *Queries) ListProspects(ctx context.Context, arg ListProspectsParams) ([]ListProspectsRow, error) {
	rows, err := q.db.Query(ctx, listProspects, arg.Season, arg.Position, arg.League)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProspectsRow{}
	for rows.Next() {
		var i ListProspectsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Position,
			&i.DraftYear,
			&i.DraftOverall,
			&i.League,
			&i.Source,
			&i.EliteprospectsUrl,
			&i.TeamName,
			&i.Season,
			&i.GamesPlayed,
			&i.Goals,
			&i.Assists,
			&i.Points,
			&i.PlusMinus,
			&i.Pim,
			&i.Wins,
			&i.Losses,
			&i.OtLosses,
			&i.Shutouts,
			&i.Saves,
			&i.Shots,
			&i.Gaa,
			&i.SvPct,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGoalieSeasonStats = `-- name: UpsertGoalieSeasonStats :exec
INSERT INTO prospect_season_stats (
    prospect_id, season, team_name, games_played,
    wins, losses, ot_losses, shutouts, saves, shots, gaa, sv_pct, fetched_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, now()
)
ON CONFLICT (prospect_id, season) DO UPDATE SET
    team_name    = EXCLUDED.team_name,
    games_played = EXCLUDED.games_played,
    wins         = EXCLUDED.wins,
    losses       = EXCLUDED.losses,
    ot_losses    = EXCLUDED.ot_losses,
    shutouts     = EXCLUDED.shutouts,
    saves        = EXCLUDED.saves,
    shots        = EXCLUDED.shots,
    gaa          = EXCLUDED.gaa,
    sv_pct       = EXCLUDED.sv_pct,
    fetched_at   = now()
`

type UpsertGoalieSeasonStatsParams struct {
	ProspectID  int64          `json:"prospect_id"`
	Season      string         `json:"season"`
	TeamName    *string        `json:"team_name"`
	GamesPlayed int32          `json:"games_played"`
	Wins        *int32         `json:"wins"`
	Losses      *int32         `json:"losses"`
	OtLosses    *int32         `json:"ot_losses"`
	Shutouts    *int32         `json:"shutouts"`
	Saves       *int32         `json:"saves"`
	Shots       *int32         `json:"shots"`
	Gaa         pgtype.Numeric `json:"gaa"`
	SvPct       pgtype.Numeric `json:"sv_pct"`
}

// Goalie counterpart of UpsertSeasonStats; skater counters are left at their
// defaults (0) and untouched on conflict.
func (q *Queries) UpsertGoalieSeasonStats(ctx context.Context, arg UpsertGoalieSeasonStatsParams) error {
	_, err := q.db.Exec(ctx, upsertGoalieSeasonStats,
		arg.ProspectID,
		arg.Season,
		arg.TeamName,
		arg.GamesPlayed,
		arg.Wins,
		arg.Losses,
		arg.OtLosses,
		arg.Shutouts,
		arg.Saves,
		arg.Shots,
		arg.Gaa,
		arg.SvPct,
	)
	return err
}

const upsertSeasonStats = `-- name: UpsertSeasonStats :exec
INSERT INTO prospect_season_stats (
    prospect_id, season, team_name,
    games_played, goals, assists, points, plus_minus, pim, fetched_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, now()
)
ON CONFLICT (prospect_id, season) DO UPDATE SET
    team_name    = EXCLUDED.team_name,
    games_played = EXCLUDED.games_played,
    goals        = EXCLUDED.goals,
    assists      = EXCLUDED.assists,
    points       = EXCLUDED.points,
    plus_minus   = EXCLUDED.plus_minus,
    pim          = EXCLUDED.pim,
    fetched_at   = now()
`

type UpsertSeasonStatsParams struct {
	ProspectID  int64   `json:"prospect_id"`
	Season      string  `json:"season"`
	TeamName    *string `json:"team_name"`
	GamesPlayed int32   `json:"games_played"`
	Goals       int32   `json:"goals"`
	Assists     int32   `json:"assists"`
	Points      int32   `json:"points"`
	PlusMinus   int32   `json:"plus_minus"`
	Pim         int32   `json:"pim"`
}

func (q *Queries) UpsertSeasonStats(ctx context.Context, arg UpsertSeasonStatsParams) error {
	_, err := q.db.Exec(ctx, upsertSeasonStats,
		arg.ProspectID,
		arg.Season,
		arg.TeamName,
		arg.GamesPlayed,
		arg.Goals,
		arg.Assists,
		arg.Points,
		arg.PlusMinus,
		arg.Pim,
	)
	return err
}
